using System.Collections.Generic;

namespace GSCDecompiler
{

    public partial class Form1
    {
        //when referencing a function, the hash after the name hash is the name of the gsc that it is in (not with .gsc or path)
        //all hashes are canonical string, they go by these rules:
        //RULES:
        //1. has to be just the filename, no directory or file extension (.gsc/csc)
        //1. remove any _ at the start
        //2. remove _shared suffix
        //scene_debug_shared doesn't do it fuck you scene_debug_shared, damn the devs for not making it canonical they must just name and hash the gsc file and then change the name so stupid

        //struct Imports //changes opcodes that call either gsc functions or internal functions from their hash to an offset that vm_execute can easily jump to
        //{
        //    int function_hashed_name;
        //    int gsc_file_name_hash;
        //    short count;
        //    byte ParamNumber;
        //    ImportFlags Flags;
        //    int references[count];    //position of the opcode, not the hash
        //}

        //enum ImportFlags                  //the X means that they have variable values, OP_CallBuiltin has 0x02 and sometimes 0x22 for some reason but it doesn't change anything at all.
        //0x00 - not seen in gsc file yet
        //0xX1 - OP_GetFunction
        //0xX2 - OP_ScriptFunctionCall, OP_CallBuiltin
        //0xX3 - OP_ScriptThreadCall
        //0xX4 - OP_ScriptMethodCall, OP_CallBuiltinMethod
        //0xX5 - OP_ScriptMethodThreadCall

        //struct StringTable //changes OP_get(I)String's value into a const string
        //{
        //    short StringPointer;
        //    byte TimesUsed;
        //    byte type;                        //always 0, if not xex linker errors out
        //    int referencesInGSC[TimesUsed];   //position of the string short, not the opcode
        //}

        //struct Exports //lists all functions inside he gsc file
        //{
        //    int Checksum;
        //    int Func_start;
        //    int hashed_name;
        //    int gsc_  file_name_hash;
        //    byte param_amount;
        //    ExportFlags flags;
        //    short unknown;
        //};

        //enum ExportFlags  //on bo3 pc unk and unk2 are the same as no flags, and i can't see any difference so i'd assume they are the same
        //0x00 - unk
        //0x01 - unk2
        //0x02 - autoexec

        //struct DevString //this references op_getstring's values
        //{
        //    short stringshort(?)
        //    byte amount
        //    byte flags(?)
        //    int references[amount]
        //}

        public void InitDictionary()
        {
            OPCodeDict = new Dictionary<int, int>()
            {
                {0x00, (int)OPCodeNames.OP_Invalid                                          },
                {0x01, (int)OPCodeNames.OP_Invalid                                          },
                {0x02, (int)OPCodeNames.OP_ClearParams                                   },
                {0x03, (int)OPCodeNames.OP_End                                           },
                {0x04, (int)OPCodeNames.OP_CallBuiltin                                   },
                {0x05, (int)OPCodeNames.OP_EvalLocalVariableRef                          },
                {0x06, (int)OPCodeNames.OP_Invalid                                          },
                {0x07, (int)OPCodeNames.OP_PreScriptCall                                 },
                {0x08, (int)OPCodeNames.OP_Invalid                                          },
                {0x09, (int)OPCodeNames.OP_CheckClearParams                              },
                {0x0A, (int)OPCodeNames.OP_EvalLocalVariable                             },
                {0x0B, (int)OPCodeNames.OP_Invalid                                          },
                {0x0C, (int)OPCodeNames.OP_Invalid                                          },
                {0x0D, (int)OPCodeNames.OP_Invalid                                          },
                {0x0E, (int)OPCodeNames.OP_Invalid                                          },
                {0x0F, (int)OPCodeNames.OP_Invalid                                          },
                {0x10, (int)OPCodeNames.OP_Invalid                                          },
                {0x11, (int)OPCodeNames.OP_GetUIntPointer                                },
                {0x12, (int)OPCodeNames.OP_BoolNot                                       },
                {0x13, (int)OPCodeNames.OP_CreateLocalVariable                           },
                {0x14, (int)OPCodeNames.OP_JumpOnTrue                                    },
                {0x15, (int)OPCodeNames.OP_GetSelfObject                                 },
                {0x16, (int)OPCodeNames.OP_Inc                                           },
                {0x17, (int)OPCodeNames.OP_GetByte                                       },
                {0x18, (int)OPCodeNames.OP_Bit_And                                       },
                {0x19, (int)OPCodeNames.OP_WaitRealTime                                      },
                {0x1A, (int)OPCodeNames.OP_ScriptThreadCallPointer                       },
                {0x1B, (int)OPCodeNames.OP_GetString                                     },
                {0x1C, (int)OPCodeNames.OP_GetIString                                    },
                {0x1D, (int)OPCodeNames.OP_GetWorld                                     },
                {0x1E, (int)OPCodeNames.OP_GetZero                                       },
                {0x1F, (int)OPCodeNames.OP_ShiftLeft                                     },
                {0x20, (int)OPCodeNames.OP_GetGame                                       },
                {0x21, (int)OPCodeNames.OP_SuperNotEqual                                 },
                {0x22, (int)OPCodeNames.OP_JumpOnFalseExpr                               },
                {0x23, (int)OPCodeNames.OP_ScriptFunctionCallPointer                     },
                {0x24, (int)OPCodeNames.OP_Invalid                                          },
                {0x25, (int)OPCodeNames.OP_ShiftRight                                    },
                {0x26, (int)OPCodeNames.OP_GetGameRef                                    },
                {0x27, (int)OPCodeNames.OP_ClassFunctionCall                             },
                {0x28, (int)OPCodeNames.OP_GetFunction                                   },
                {0x29, (int)OPCodeNames.OP_GetIString                                    },
                {0x2A, (int)OPCodeNames.OP_EndSwitch                                     },
                {0x2B, (int)OPCodeNames.OP_ClassFunctionThreadCall                       },
                {0x2C, (int)OPCodeNames.OP_GetClassesObject                              },
                {0x2D, (int)OPCodeNames.OP_FirstArrayKey                                 },
                {0x2E, (int)OPCodeNames.OP_Return                                        },
                {0x2F, (int)OPCodeNames.OP_Plus                                          },
                {0x30, (int)OPCodeNames.OP_ScriptFunctionCall                            },
                {0x31, (int)OPCodeNames.OP_IsDefined                                     },
                {0x32, (int)OPCodeNames.OP_ScriptMethodCall                              },
                {0x33, (int)OPCodeNames.OP_Invalid                                          },
                {0x34, (int)OPCodeNames.OP_ScriptMethodCall                              },
                {0x35, (int)OPCodeNames.OP_SuperNotEqual                                 },
                {0x36, (int)OPCodeNames.OP_GetLevel                                      },
                {0x37, (int)OPCodeNames.OP_GetNegUnsignedShort                           },
                {0x38, (int)OPCodeNames.OP_GetNegByte                                    },
                {0x39, (int)OPCodeNames.OP_GetLongUndefined                              },
                {0x3A, (int)OPCodeNames.OP_ScriptMethodCall                              },
                {0x3B, (int)OPCodeNames.OP_GetFunction                                   },
                {0x3C, (int)OPCodeNames.OP_Invalid                                          },
                {0x3D, (int)OPCodeNames.OP_GetFunction                                   },
                {0x3E, (int)OPCodeNames.OP_ClassFunctionCall                             },
                {0x3F, (int)OPCodeNames.OP_Notify                                        },
                {0x40, (int)OPCodeNames.OP_JumpOnTrue                                    },
                {0x41, (int)OPCodeNames.OP_EndOn                                         },
                {0x42, (int)OPCodeNames.OP_NextArrayKey                                  },
                {0x43, (int)OPCodeNames.OP_GetAnimation                                  },
                {0x44, (int)OPCodeNames.OP_LessThan                                      },
                {0x45, (int)OPCodeNames.OP_EvalSelfFieldVariableRef                      },
                {0x46, (int)OPCodeNames.OP_GetString                                     },
                {0x47, (int)OPCodeNames.OP_DecTop                                        },
                {0x48, (int)OPCodeNames.OP_GetUndefined                                  },
                {0x49, (int)OPCodeNames.OP_SetVariableField                              },
                {0x4A, (int)OPCodeNames.OP_EvalLevelFieldVariable                        },
                {0x4B, (int)OPCodeNames.OP_GetEmptyArray                                 },
                {0x4C, (int)OPCodeNames.OP_ClearArray                                    },
                {0x4D, (int)OPCodeNames.OP_Invalid                                          },
                {0x4E, (int)OPCodeNames.OP_WaitTill                                      },
                {0x4F, (int)OPCodeNames.OP_GetApiFunction                                },
                {0x50, (int)OPCodeNames.OP_WaitTillFrameEnd                              },
                {0x51, (int)OPCodeNames.OP_EndSwitch                                     },
                {0x52, (int)OPCodeNames.OP_GetSelf                                       },
                {0x53, (int)OPCodeNames.OP_GetFloat                                      },
                {0x54, (int)OPCodeNames.OP_ClearArray                                    },
                {0x55, (int)OPCodeNames.OP_Wait                                          },
                {0x56, (int)OPCodeNames.OP_GetHash                                       },
                {0x57, (int)OPCodeNames.OP_GetClassesObject                              },
                {0x58, (int)OPCodeNames.OP_Invalid                                          },
                {0x59, (int)OPCodeNames.OP_GetWorldObject                                     },
                {0x5A, (int)OPCodeNames.OP_GetFloat                                      },
                {0x5B, (int)OPCodeNames.OP_WaitTill                                      },
                {0x5C, (int)OPCodeNames.OP_SizeOf                                        },
                {0x5D, (int)OPCodeNames.OP_EvalArrayRef                                  },
                {0x5E, (int)OPCodeNames.OP_ScriptMethodCallPointer                       },
                {0x5F, (int)OPCodeNames.OP_EvalLevelFieldVariable                        },
                {0x60, (int)OPCodeNames.OP_BoolComplement                                },
                {0x61, (int)OPCodeNames.OP_Bit_And                                       },
                {0x62, (int)OPCodeNames.OP_Bit_Xor                                       },
                {0x63, (int)OPCodeNames.OP_Modulus                                       },
                {0x64, (int)OPCodeNames.OP_EvalArray                                     },
                {0x65, (int)OPCodeNames.OP_EvalFieldVariable                             },
                {0x66, (int)OPCodeNames.OP_SuperEqual                                    },
                {0x67, (int)OPCodeNames.OP_GetClasses                                     },
                {0x68, (int)OPCodeNames.OP_Bit_Or                                        },
                {0x69, (int)OPCodeNames.OP_LessThanOrEqualTo                             },
                {0x6A, (int)OPCodeNames.OP_DecTop                                        },
                {0x6B, (int)OPCodeNames.OP_GetObjectType                                 },
                {0x6C, (int)OPCodeNames.OP_Multiply                                      },
                {0x6D, (int)OPCodeNames.OP_Vector                                        },
                {0x6E, (int)OPCodeNames.OP_GetTime                                       },
                {0x6F, (int)OPCodeNames.OP_SizeOf                                        },
                {0x70, (int)OPCodeNames.OP_GetFloat                                      },
                {0x71, (int)OPCodeNames.OP_GetWorldObject                                     },
                {0x72, (int)OPCodeNames.OP_EvalLocalVariableRefCached                    },
                {0x73, (int)OPCodeNames.OP_ScriptFunctionCallPointer                     },
                {0x74, (int)OPCodeNames.OP_Switch                                        },
                {0x75, (int)OPCodeNames.OP_Invalid                                          },
                {0x76, (int)OPCodeNames.OP_Invalid                                          },
                {0x77, (int)OPCodeNames.OP_GetTime                                       },
                {0x78, (int)OPCodeNames.OP_Vector                                        },
                {0x79, (int)OPCodeNames.OP_Invalid                                          },
                {0x7A, (int)OPCodeNames.OP_GetHash                                       },
                {0x7B, (int)OPCodeNames.OP_CastBool                                      },
                {0x7C, (int)OPCodeNames.OP_GetAnimation                                  },
                {0x7D, (int)OPCodeNames.OP_Invalid                                          },
                {0x7E, (int)OPCodeNames.OP_ShiftRight                                    },
                {0x7F, (int)OPCodeNames.OP_Inc                                           },
                {0x80, (int)OPCodeNames.OP_NotEqual                                      },
                {0x81, (int)OPCodeNames.OP_JumpOnTrue                                    },
                {0x82, (int)OPCodeNames.OP_Invalid                                          },
                {0x83, (int)OPCodeNames.OP_GetAnimation                                  },
                {0x84, (int)OPCodeNames.OP_GreaterThan                                   },
                {0x85, (int)OPCodeNames.OP_EvalSelfFieldVariable                         },
                {0x86, (int)OPCodeNames.OP_Invalid                                          },
                {0x87, (int)OPCodeNames.OP_GetAnim                                       },
                {0x88, (int)OPCodeNames.OP_CreateLocalVariable                           },
                {0x89, (int)OPCodeNames.OP_Jump                                          },
                {0x8A, (int)OPCodeNames.OP_EvalArrayRef                                  },
                {0x8B, (int)OPCodeNames.OP_EvalLocalVariableCached                       },
                {0x8C, (int)OPCodeNames.OP_ScriptMethodThreadCall                        },
                {0x8D, (int)OPCodeNames.OP_Invalid                                          },
                {0x8E, (int)OPCodeNames.OP_Dec                                           },
                {0x8F, (int)OPCodeNames.OP_Equal                                         },
                {0x90, (int)OPCodeNames.OP_Notify                                        },
                {0x91, (int)OPCodeNames.OP_ClassFunctionThreadCall                       },
                {0x92, (int)OPCodeNames.OP_SetWaittillVariableFieldCached                },
                {0x93, (int)OPCodeNames.OP_BoolComplement                                },
                {0x94, (int)OPCodeNames.OP_BoolNot                                       },
                {0x95, (int)OPCodeNames.OP_GetWorld                                     },
                {0x96, (int)OPCodeNames.OP_Minus                                         },
                {0x97, (int)OPCodeNames.OP_Invalid                                          },
                {0x98, (int)OPCodeNames.OP_CastFieldObject                               },
                {0x99, (int)OPCodeNames.OP_GetVector                                     },
                {0x9A, (int)OPCodeNames.OP_Divide                                        },
                {0x9B, (int)OPCodeNames.OP_ScriptThreadCallPointer                       },
                {0x9C, (int)OPCodeNames.OP_Jump                                          },
                {0x9D, (int)OPCodeNames.OP_GetUndefined                                  },
                {0x9E, (int)OPCodeNames.OP_GetByte                                       },
                {0x9F, (int)OPCodeNames.OP_JumpOnFalse                                   },
                {0xA0, (int)OPCodeNames.OP_CallBuiltinMethod                             },
                {0xA1, (int)OPCodeNames.OP_EvalFieldVariableRef                          },
                {0xA2, (int)OPCodeNames.OP_ScriptThreadCall                              },
                {0xA3, (int)OPCodeNames.OP_Invalid                                          },
                {0xA4, (int)OPCodeNames.OP_Invalid                                          },
                {0xA5, (int)OPCodeNames.OP_WaitTillMatch                                 },
                {0xA6, (int)OPCodeNames.OP_GetSelf                                       },
                {0xA7, (int)OPCodeNames.OP_Invalid                                          },
                {0xA8, (int)OPCodeNames.OP_SetWaittillVariableFieldCached                },
                {0xA9, (int)OPCodeNames.OP_SuperEqual                                    },
                {0xAA, (int)OPCodeNames.OP_EndOn                                         },
                {0xAB, (int)OPCodeNames.OP_GetString                                     },
                {0xAC, (int)OPCodeNames.OP_Jump                                          },
                {0xAD, (int)OPCodeNames.OP_GetNegByte                                    },
                {0xAE, (int)OPCodeNames.OP_GreaterThanOrEqualTo                          },
                {0xAF, (int)OPCodeNames.OP_ClearFieldVariable                            },
                {0xB0, (int)OPCodeNames.OP_IsDefined                                     },
                {0xB1, (int)OPCodeNames.OP_GetUndefined                                  },
                {0xB2, (int)OPCodeNames.OP_VectorConstant                                },
                {0xB3, (int)OPCodeNames.OP_Invalid                                          },
                {0xB4, (int)OPCodeNames.OP_EvalFieldVariableRef                          },
                {0xB5, (int)OPCodeNames.OP_GetAnim                                       },
                {0xB6, (int)OPCodeNames.OP_GetApiFunction                                },
                {0xB7, (int)OPCodeNames.OP_GetGameRef                                    },
                {0xB8, (int)OPCodeNames.OP_JumpOnTrueExpr                                },
                {0xB9, (int)OPCodeNames.OP_GetLongUndefined                              },
                {0xBA, (int)OPCodeNames.OP_Modulus                                       },
                {0xBB, (int)OPCodeNames.OP_GetInteger                                    },
                {0xBC, (int)OPCodeNames.OP_Jump                                          },
                {0xBD, (int)OPCodeNames.OP_GetZero                                       },
                {0xBE, (int)OPCodeNames.OP_BoolComplement                                },
                {0xBF, (int)OPCodeNames.OP_SetVariableField                              },
                {0xC0, (int)OPCodeNames.OP_Multiply                                      },
                {0xC1, (int)OPCodeNames.OP_CastBool                                      },
                {0xC2, (int)OPCodeNames.OP_JumpOnFalse                                   },
                {0xC3, (int)OPCodeNames.OP_Bit_Or                                        },
                {0xC4, (int)OPCodeNames.OP_Invalid                                          },
                {0xC5, (int)OPCodeNames.OP_Invalid                                          },
                {0xC6, (int)OPCodeNames.OP_SafeSetVariableFieldCached                    },
                {0xC7, (int)OPCodeNames.OP_SetVariableField                              },
                {0xC8, (int)OPCodeNames.OP_GetWorld                                     },
                {0xC9, (int)OPCodeNames.OP_CallBuiltinMethod                             },
                {0xCA, (int)OPCodeNames.OP_GetLevel                                      },
                {0xCB, (int)OPCodeNames.OP_GetUndefined                                  },
                {0xCC, (int)OPCodeNames.OP_Invalid                                          },
                {0xCD, (int)OPCodeNames.OP_Equal                                         },
                {0xCE, (int)OPCodeNames.OP_GetEmptyArray                                 },
                {0xCF, (int)OPCodeNames.OP_WaitTillMatch                                 },
                {0xD0, (int)OPCodeNames.OP_FirstArrayKey                                 },
                {0xD1, (int)OPCodeNames.OP_EndOn                                         },
                {0xD2, (int)OPCodeNames.OP_EvalSelfFieldVariableRef                      },
                {0xD3, (int)OPCodeNames.OP_Wait                                          },
                {0xD4, (int)OPCodeNames.OP_ScriptThreadCall                              },
                {0xD5, (int)OPCodeNames.OP_VectorScale                                   },
                {0xD6, (int)OPCodeNames.OP_EvalLevelFieldVariableRef                     },
                {0xD7, (int)OPCodeNames.OP_VectorConstant                                },
                {0xD8, (int)OPCodeNames.OP_Invalid                                          },
                {0xD9, (int)OPCodeNames.OP_EvalFieldVariable                             },
                {0xDA, (int)OPCodeNames.OP_Switch                                        },
                {0xDB, (int)OPCodeNames.OP_Jump                                          },
                {0xDC, (int)OPCodeNames.OP_GetApiFunction                                },
                {0xDD, (int)OPCodeNames.OP_Invalid                                          },
                {0xDE, (int)OPCodeNames.OP_WaitTillFrameEnd                              },
                {0xDF, (int)OPCodeNames.OP_EvalArray                                     },
                {0xE0, (int)OPCodeNames.OP_Plus                                          },
                {0xE1, (int)OPCodeNames.OP_GetLevelObject                                },
                {0xE2, (int)OPCodeNames.OP_ScriptMethodCallPointer                       },
                {0xE3, (int)OPCodeNames.OP_GetAnimObject                                 },
                {0xE4, (int)OPCodeNames.OP_EndSwitch                                     },
                {0xE5, (int)OPCodeNames.OP_GetUIntPointer                                },
                {0xE6, (int)OPCodeNames.OP_JumpOnFalse                                   },
                {0xE7, (int)OPCodeNames.OP_Invalid                                   },
                {0xE8, (int)OPCodeNames.OP_SafeDecTop                                    },
                {0xE9, (int)OPCodeNames.OP_GetUnsignedShort                              },
                {0xEA, (int)OPCodeNames.OP_WaitRealTime                                      },
                {0xEB, (int)OPCodeNames.OP_SafeDecTop                                    },
                {0xEC, (int)OPCodeNames.OP_WaitRealTime                                      },
                {0xED, (int)OPCodeNames.OP_GetUndefined                                  },
                {0xEE, (int)OPCodeNames.OP_Invalid                                          },
                {0xEF, (int)OPCodeNames.OP_EvalLevelFieldVariableRef                     },
                {0xF0, (int)OPCodeNames.OP_GetLevel                                      },
                {0xF1, (int)OPCodeNames.OP_NextArrayKey                                  },
                {0xF2, (int)OPCodeNames.OP_Invalid                                          },
                {0xF3, (int)OPCodeNames.OP_GetClassesObject                              },
                {0xF4, (int)OPCodeNames.OP_EvalLocalVariableCached                       },
                {0xF5, (int)OPCodeNames.OP_GreaterThanOrEqualTo                          },
                {0xF6, (int)OPCodeNames.OP_Multiply                                      },
                {0xF7, (int)OPCodeNames.OP_VectorScale                                   },
                {0xF8, (int)OPCodeNames.OP_Invalid                                          },
                {0xF9, (int)OPCodeNames.OP_ClearFieldVariable                            },
                {0xFA, (int)OPCodeNames.OP_ScriptMethodThreadCallPointer                 },
                {0xFB, (int)OPCodeNames.OP_Plus                                          },
                {0xFC, (int)OPCodeNames.OP_NotEqual                                      },
                {0xFD, (int)OPCodeNames.OP_Return                                        },
                {0xFE, (int)OPCodeNames.OP_WaitTill                                      },
                {0xFF, (int)OPCodeNames.OP_NextArrayKey                                  }
            };
        }
        public enum OPCodeNames : byte
        {
            OP_Invalid,
            OP_ClearParams,
            OP_End,
            OP_CallBuiltin,
            OP_EvalLocalVariableRef,
            OP_PreScriptCall,
            OP_CheckClearParams,
            OP_EvalLocalVariable,
            OP_GetUIntPointer,
            OP_BoolNot,
            OP_CreateLocalVariable,
            OP_JumpOnTrue,
            OP_GetSelfObject,
            OP_Inc,
            OP_GetByte,
            OP_Bit_And,
            OP_WaitRealTime,
            OP_ScriptThreadCallPointer,
            OP_GetString,
            OP_GetIString,
            OP_GetWorld,
            OP_GetZero,
            OP_ShiftLeft,
            OP_GetGame,
            OP_SuperNotEqual,
            OP_JumpOnFalseExpr,
            OP_ScriptFunctionCallPointer,
            OP_ShiftRight,
            OP_GetGameRef,
            OP_ClassFunctionCall,
            OP_GetFunction,
            OP_EndSwitch,
            OP_ClassFunctionThreadCall,
            OP_GetClassesObject,
            OP_FirstArrayKey,
            OP_Return,
            OP_Plus,
            OP_ScriptFunctionCall,
            OP_IsDefined,
            OP_ScriptMethodCall,
            OP_GetLevel,
            OP_GetNegUnsignedShort,
            OP_GetNegByte,
            OP_GetLongUndefined,
            OP_Notify,
            OP_EndOn,
            OP_NextArrayKey,
            OP_GetAnimation,
            OP_LessThan,
            OP_EvalSelfFieldVariableRef,
            OP_DecTop,
            OP_GetUndefined,
            OP_SetVariableField,
            OP_EvalLevelFieldVariable,
            OP_GetEmptyArray,
            OP_ClearArray,
            OP_WaitTill,
            OP_GetApiFunction,
            OP_WaitTillFrameEnd,
            OP_GetSelf,
            OP_GetFloat,
            OP_Wait,
            OP_GetHash,
            OP_GetWorldObject,
            OP_SizeOf,
            OP_EvalArrayRef,
            OP_ScriptMethodCallPointer,
            OP_BoolComplement,
            OP_Bit_Xor,
            OP_Modulus,
            OP_EvalArray,
            OP_EvalFieldVariable,
            OP_SuperEqual,
            OP_GetClasses,
            OP_Bit_Or,
            OP_LessThanOrEqualTo,
            OP_GetObjectType,
            OP_Multiply,
            OP_Vector,
            OP_GetTime,
            OP_EvalLocalVariableRefCached,
            OP_Switch,
            OP_CastBool,
            OP_NotEqual,
            OP_GreaterThan,
            OP_EvalSelfFieldVariable,
            OP_GetAnim,
            OP_Jump,
            OP_EvalLocalVariableCached,
            OP_ScriptMethodThreadCall,
            OP_Dec,
            OP_Equal,
            OP_SetWaittillVariableFieldCached,
            OP_Minus,
            OP_CastFieldObject,
            OP_GetVector,
            OP_Divide,
            OP_JumpOnFalse,
            OP_CallBuiltinMethod,
            OP_EvalFieldVariableRef,
            OP_ScriptThreadCall,
            OP_WaitTillMatch,
            OP_GreaterThanOrEqualTo,
            OP_ClearFieldVariable,
            OP_VectorConstant,
            OP_JumpOnTrueExpr,
            OP_GetInteger,
            OP_SafeSetVariableFieldCached,
            OP_VectorScale,
            OP_EvalLevelFieldVariableRef,
            OP_GetLevelObject,
            OP_GetAnimObject,
            OP_SafeDecTop,
            OP_GetUnsignedShort,
            OP_ScriptMethodThreadCallPointer
        }
    }
}